create table if not exists "user"
(
    id bigint generated by default as identity not null,
    first_name     varchar(255) not null,
    last_name      varchar(255) not null,
    email          varchar(255) not null,
    birth_date     date         not null,
    address        varchar(255),
    phone_number   varchar(255),
    unique (email)
)